---
swagger: "2.0"
info:
  version: "1.0"
  title: "A Bit of Everything"
  contact:
    name: "gRPC-Gateway project"
    url: "https://github.com/grpc-ecosystem/grpc-gateway"
    email: "none@example.com"
schemes:
- "http"
- "https"
- "wss"
consumes:
- "application/json"
- "application/x-foo-mime"
produces:
- "application/json"
- "application/x-foo-mime"
security:
- ApiKeyAuth: []
  BasicAuth: []
- ApiKeyAuth: []
  OAuth2:
  - "read"
  - "write"
paths:
  /v1/example/a_bit_of_everything:
    post:
      tags:
      - "ABitOfEverythingService"
      operationId: "CreateBody"
      parameters:
      - in: "body"
        name: "body"
        required: true
        schema:
          $ref: "#/definitions/examplepbABitOfEverything"
        x-exportParamName: "Body"
      responses:
        200:
          description: ""
          schema:
            $ref: "#/definitions/examplepbABitOfEverything"
  /v1/example/a_bit_of_everything/echo/{value}:
    get:
      tags:
      - "echo service"
      - "echo rpc"
      summary: "Summary: Echo rpc"
      description: "Description Echo"
      operationId: "Echo"
      parameters:
      - name: "value"
        in: "path"
        required: true
        type: "string"
        x-exportParamName: "Value"
      responses:
        200:
          description: ""
          schema:
            $ref: "#/definitions/subStringMessage"
      externalDocs:
        description: "Find out more Echo"
        url: "https://github.com/grpc-ecosystem/grpc-gateway"
  /v1/example/a_bit_of_everything/query/{uuid}:
    get:
      tags:
      - "ABitOfEverythingService"
      operationId: "GetQuery"
      parameters:
      - name: "uuid"
        in: "path"
        required: true
        type: "string"
        x-exportParamName: "Uuid"
      - name: "single_nested.name"
        in: "query"
        description: "name is nested field."
        required: false
        type: "string"
        x-exportParamName: "SingleNestedName"
      - name: "single_nested.amount"
        in: "query"
        required: false
        type: "integer"
        format: "int64"
        x-exportParamName: "SingleNestedAmount"
      - name: "single_nested.ok"
        in: "query"
        description: " - FALSE: FALSE is false.\n - TRUE: TRUE is true."
        required: false
        type: "string"
        default: "FALSE"
        enum:
        - "FALSE"
        - "TRUE"
        x-exportParamName: "SingleNestedOk"
      - name: "floatValue"
        in: "query"
        required: false
        type: "number"
        format: "float"
        x-exportParamName: "FloatValue"
      - name: "doubleValue"
        in: "query"
        required: false
        type: "number"
        format: "double"
        x-exportParamName: "DoubleValue"
      - name: "int64Value"
        in: "query"
        required: false
        type: "string"
        format: "int64"
        x-exportParamName: "Int64Value"
      - name: "uint64Value"
        in: "query"
        required: false
        type: "string"
        format: "uint64"
        x-exportParamName: "Uint64Value"
      - name: "int32Value"
        in: "query"
        required: false
        type: "integer"
        format: "int32"
        x-exportParamName: "Int32Value"
      - name: "fixed64Value"
        in: "query"
        required: false
        type: "string"
        format: "uint64"
        x-exportParamName: "Fixed64Value"
      - name: "fixed32Value"
        in: "query"
        required: false
        type: "integer"
        format: "int64"
        x-exportParamName: "Fixed32Value"
      - name: "boolValue"
        in: "query"
        required: false
        type: "boolean"
        format: "boolean"
        x-exportParamName: "BoolValue"
      - name: "stringValue"
        in: "query"
        required: false
        type: "string"
        x-exportParamName: "StringValue"
      - name: "bytesValue"
        in: "query"
        required: false
        type: "string"
        format: "byte"
        x-exportParamName: "BytesValue"
      - name: "uint32Value"
        in: "query"
        required: false
        type: "integer"
        format: "int64"
        x-exportParamName: "Uint32Value"
      - name: "enumValue"
        in: "query"
        description: " - ZERO: ZERO means 0\n - ONE: ONE means 1"
        required: false
        type: "string"
        default: "ZERO"
        enum:
        - "ZERO"
        - "ONE"
        x-exportParamName: "EnumValue"
      - name: "sfixed32Value"
        in: "query"
        required: false
        type: "integer"
        format: "int32"
        x-exportParamName: "Sfixed32Value"
      - name: "sfixed64Value"
        in: "query"
        required: false
        type: "string"
        format: "int64"
        x-exportParamName: "Sfixed64Value"
      - name: "sint32Value"
        in: "query"
        required: false
        type: "integer"
        format: "int32"
        x-exportParamName: "Sint32Value"
      - name: "sint64Value"
        in: "query"
        required: false
        type: "string"
        format: "int64"
        x-exportParamName: "Sint64Value"
      - name: "repeatedStringValue"
        in: "query"
        required: false
        type: "array"
        items:
          type: "string"
        x-exportParamName: "RepeatedStringValue"
      - name: "oneofString"
        in: "query"
        required: false
        type: "string"
        x-exportParamName: "OneofString"
      - name: "nonConventionalNameValue"
        in: "query"
        required: false
        type: "string"
        x-exportParamName: "NonConventionalNameValue"
      - name: "timestampValue"
        in: "query"
        required: false
        type: "string"
        format: "date-time"
        x-exportParamName: "TimestampValue"
      - name: "repeatedEnumValue"
        in: "query"
        description: "repeated enum value. it is comma-separated in query.\n\n - ZERO:\
          \ ZERO means 0\n - ONE: ONE means 1"
        required: false
        type: "array"
        items:
          type: "string"
          enum:
          - "ZERO"
          - "ONE"
        x-exportParamName: "RepeatedEnumValue"
      responses:
        200:
          description: ""
          schema:
            $ref: "#/definitions/protobufEmpty"
      externalDocs:
        description: "Find out more about GetQuery"
        url: "https://github.com/grpc-ecosystem/grpc-gateway"
      deprecated: true
  ? /v1/example/a_bit_of_everything/{float_value}/{double_value}/{int64_value}/separator/{uint64_value}/{int32_value}/{fixed64_value}/{fixed32_value}/{bool_value}/{string_value}/{uint32_value}/{sfixed32_value}/{sfixed64_value}/{sint32_value}/{sint64_value}/{nonConventionalNameValue}
  : post:
      tags:
      - "ABitOfEverythingService"
      operationId: "Create"
      parameters:
      - name: "float_value"
        in: "path"
        required: true
        type: "number"
        format: "float"
        x-exportParamName: "FloatValue"
      - name: "double_value"
        in: "path"
        required: true
        type: "number"
        format: "double"
        x-exportParamName: "DoubleValue"
      - name: "int64_value"
        in: "path"
        required: true
        type: "string"
        format: "int64"
        x-exportParamName: "Int64Value"
      - name: "uint64_value"
        in: "path"
        required: true
        type: "string"
        format: "uint64"
        x-exportParamName: "Uint64Value"
      - name: "int32_value"
        in: "path"
        required: true
        type: "integer"
        format: "int32"
        x-exportParamName: "Int32Value"
      - name: "fixed64_value"
        in: "path"
        required: true
        type: "string"
        format: "uint64"
        x-exportParamName: "Fixed64Value"
      - name: "fixed32_value"
        in: "path"
        required: true
        type: "integer"
        format: "int64"
        x-exportParamName: "Fixed32Value"
      - name: "bool_value"
        in: "path"
        required: true
        type: "boolean"
        format: "boolean"
        x-exportParamName: "BoolValue"
      - name: "string_value"
        in: "path"
        required: true
        type: "string"
        x-exportParamName: "StringValue"
      - name: "uint32_value"
        in: "path"
        required: true
        type: "integer"
        format: "int64"
        x-exportParamName: "Uint32Value"
      - name: "sfixed32_value"
        in: "path"
        required: true
        type: "integer"
        format: "int32"
        x-exportParamName: "Sfixed32Value"
      - name: "sfixed64_value"
        in: "path"
        required: true
        type: "string"
        format: "int64"
        x-exportParamName: "Sfixed64Value"
      - name: "sint32_value"
        in: "path"
        required: true
        type: "integer"
        format: "int32"
        x-exportParamName: "Sint32Value"
      - name: "sint64_value"
        in: "path"
        required: true
        type: "string"
        format: "int64"
        x-exportParamName: "Sint64Value"
      - name: "nonConventionalNameValue"
        in: "path"
        required: true
        type: "string"
        x-exportParamName: "NonConventionalNameValue"
      responses:
        200:
          description: ""
          schema:
            $ref: "#/definitions/examplepbABitOfEverything"
  /v1/example/a_bit_of_everything/{single_nested.name}:
    post:
      tags:
      - "ABitOfEverythingService"
      operationId: "DeepPathEcho"
      parameters:
      - name: "single_nested.name"
        in: "path"
        required: true
        type: "string"
        x-exportParamName: "SingleNestedName"
      - in: "body"
        name: "body"
        required: true
        schema:
          $ref: "#/definitions/examplepbABitOfEverything"
        x-exportParamName: "Body"
      responses:
        200:
          description: ""
          schema:
            $ref: "#/definitions/examplepbABitOfEverything"
  /v1/example/a_bit_of_everything/{uuid}:
    get:
      tags:
      - "ABitOfEverythingService"
      operationId: "Lookup"
      parameters:
      - name: "uuid"
        in: "path"
        required: true
        type: "string"
        x-exportParamName: "Uuid"
      responses:
        200:
          description: ""
          schema:
            $ref: "#/definitions/examplepbABitOfEverything"
    put:
      tags:
      - "ABitOfEverythingService"
      operationId: "Update"
      parameters:
      - name: "uuid"
        in: "path"
        required: true
        type: "string"
        x-exportParamName: "Uuid"
      - in: "body"
        name: "body"
        required: true
        schema:
          $ref: "#/definitions/examplepbABitOfEverything"
        x-exportParamName: "Body"
      responses:
        200:
          description: ""
          schema:
            $ref: "#/definitions/protobufEmpty"
    delete:
      tags:
      - "ABitOfEverythingService"
      operationId: "Delete"
      parameters:
      - name: "uuid"
        in: "path"
        required: true
        type: "string"
        x-exportParamName: "Uuid"
      responses:
        200:
          description: ""
          schema:
            $ref: "#/definitions/protobufEmpty"
      security:
      - ApiKeyAuth: []
        OAuth2:
        - "read"
        - "write"
  /v2/example/echo:
    get:
      tags:
      - "echo service"
      - "echo rpc"
      summary: "Summary: Echo rpc"
      description: "Description Echo"
      operationId: "Echo3"
      parameters:
      - name: "value"
        in: "query"
        required: false
        type: "string"
        x-exportParamName: "Value"
      responses:
        200:
          description: ""
          schema:
            $ref: "#/definitions/subStringMessage"
      externalDocs:
        description: "Find out more Echo"
        url: "https://github.com/grpc-ecosystem/grpc-gateway"
    post:
      tags:
      - "echo service"
      - "echo rpc"
      summary: "Summary: Echo rpc"
      description: "Description Echo"
      operationId: "Echo2"
      parameters:
      - in: "body"
        name: "body"
        required: true
        schema:
          type: "string"
        x-exportParamName: "Body"
      responses:
        200:
          description: ""
          schema:
            $ref: "#/definitions/subStringMessage"
      externalDocs:
        description: "Find out more Echo"
        url: "https://github.com/grpc-ecosystem/grpc-gateway"
  /v2/example/empty:
    get:
      tags:
      - "camelCaseServiceName"
      operationId: "Empty"
      parameters: []
      responses:
        200:
          description: ""
          schema:
            $ref: "#/definitions/protobufEmpty"
  /v2/example/errorwithdetails:
    get:
      tags:
      - "ABitOfEverythingService"
      operationId: "ErrorWithDetails"
      parameters: []
      responses:
        200:
          description: ""
          schema:
            $ref: "#/definitions/protobufEmpty"
  /v2/example/postwithemptybody/{name}:
    post:
      tags:
      - "ABitOfEverythingService"
      operationId: "PostWithEmptyBody"
      parameters:
      - name: "name"
        in: "path"
        required: true
        type: "string"
        x-exportParamName: "Name"
      - in: "body"
        name: "body"
        required: true
        schema:
          $ref: "#/definitions/examplepbBody"
        x-exportParamName: "Body"
      responses:
        200:
          description: ""
          schema:
            $ref: "#/definitions/protobufEmpty"
  /v2/example/timeout:
    get:
      tags:
      - "ABitOfEverythingService"
      operationId: "Timeout"
      parameters: []
      responses:
        200:
          description: ""
          schema:
            $ref: "#/definitions/protobufEmpty"
  /v2/example/withbody/{id}:
    post:
      tags:
      - "ABitOfEverythingService"
      operationId: "GetMessageWithBody"
      parameters:
      - name: "id"
        in: "path"
        required: true
        type: "string"
        x-exportParamName: "Id"
      - in: "body"
        name: "body"
        required: true
        schema:
          $ref: "#/definitions/examplepbBody"
        x-exportParamName: "Body"
      responses:
        200:
          description: ""
          schema:
            $ref: "#/definitions/protobufEmpty"
securityDefinitions:
  ApiKeyAuth:
    type: "apiKey"
    name: "X-API-Key"
    in: "header"
  BasicAuth:
    type: "basic"
  OAuth2:
    type: "oauth2"
    authorizationUrl: "https://example.com/oauth/authorize"
    tokenUrl: "https://example.com/oauth/token"
    flow: "accessCode"
    scopes:
      admin: "Grants read and write access to administrative information"
      read: "Grants read access"
      write: "Grants write access"
definitions:
  ABitOfEverythingNested:
    type: "object"
    properties:
      name:
        type: "string"
        description: "name is nested field."
      amount:
        type: "integer"
        format: "int64"
      ok:
        $ref: "#/definitions/NestedDeepEnum"
    description: "Nested is nested type."
    example:
      amount: 0
      name: "name"
      ok: {}
  NestedDeepEnum:
    type: "string"
    description: "DeepEnum is one or zero.\n\n - FALSE: FALSE is false.\n - TRUE:\
      \ TRUE is true."
    enum:
    - "FALSE"
    - "TRUE"
    default: "FALSE"
  examplepbABitOfEverything:
    type: "object"
    properties:
      singleNested:
        $ref: "#/definitions/ABitOfEverythingNested"
      uuid:
        type: "string"
      nested:
        type: "array"
        items:
          $ref: "#/definitions/ABitOfEverythingNested"
      floatValue:
        type: "number"
        format: "float"
      doubleValue:
        type: "number"
        format: "double"
      int64Value:
        type: "string"
        format: "int64"
      uint64Value:
        type: "string"
        format: "uint64"
      int32Value:
        type: "integer"
        format: "int32"
      fixed64Value:
        type: "string"
        format: "uint64"
      fixed32Value:
        type: "integer"
        format: "int64"
      boolValue:
        type: "boolean"
        format: "boolean"
      stringValue:
        type: "string"
      bytesValue:
        type: "string"
        format: "byte"
        pattern: "^(?:[A-Za-z0-9+/]{4})*(?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)?$"
      uint32Value:
        type: "integer"
        format: "int64"
      enumValue:
        $ref: "#/definitions/examplepbNumericEnum"
      sfixed32Value:
        type: "integer"
        format: "int32"
      sfixed64Value:
        type: "string"
        format: "int64"
      sint32Value:
        type: "integer"
        format: "int32"
      sint64Value:
        type: "string"
        format: "int64"
      repeatedStringValue:
        type: "array"
        items:
          type: "string"
      oneofEmpty:
        $ref: "#/definitions/protobufEmpty"
      oneofString:
        type: "string"
      mapValue:
        type: "object"
        additionalProperties:
          $ref: "#/definitions/examplepbNumericEnum"
      mappedStringValue:
        type: "object"
        additionalProperties:
          type: "string"
      mappedNestedValue:
        type: "object"
        additionalProperties:
          $ref: "#/definitions/ABitOfEverythingNested"
      nonConventionalNameValue:
        type: "string"
      timestampValue:
        type: "string"
        format: "date-time"
      repeatedEnumValue:
        type: "array"
        title: "repeated enum value. it is comma-separated in query"
        items:
          $ref: "#/definitions/examplepbNumericEnum"
    externalDocs:
      description: "Find out more about ABitOfEverything"
      url: "https://github.com/grpc-ecosystem/grpc-gateway"
    title: "Intentionaly complicated message type to cover much features of Protobuf.\n\
      NEXT ID: 30"
    example:
      mappedNestedValue:
        key:
          amount: 0
          name: "name"
          ok: {}
      int64Value: "int64Value"
      nonConventionalNameValue: "nonConventionalNameValue"
      repeatedEnumValue:
      - null
      - null
      timestampValue: "2000-01-23T04:56:07.000+00:00"
      uuid: "uuid"
      nested:
      - amount: 0
        name: "name"
        ok: {}
      - amount: 0
        name: "name"
        ok: {}
      fixed32Value: 5
      mapValue: {}
      stringValue: "stringValue"
      sint32Value: 9
      enumValue: {}
      uint32Value: 2
      sfixed64Value: "sfixed64Value"
      repeatedStringValue:
      - "repeatedStringValue"
      - "repeatedStringValue"
      oneofEmpty: {}
      floatValue: 6.0274563
      int32Value: 5
      doubleValue: 1.4658129805029452
      uint64Value: "uint64Value"
      fixed64Value: "fixed64Value"
      sint64Value: "sint64Value"
      singleNested:
        amount: 0
        name: "name"
        ok: {}
      boolValue: true
      bytesValue: "bytesValue"
      sfixed32Value: 7
      mappedStringValue:
        key: "mappedStringValue"
      oneofString: "oneofString"
  examplepbBody:
    type: "object"
    properties:
      name:
        type: "string"
  examplepbNumericEnum:
    type: "string"
    description: "NumericEnum is one or zero.\n\n - ZERO: ZERO means 0\n - ONE: ONE\
      \ means 1"
    enum:
    - "ZERO"
    - "ONE"
    default: "ZERO"
  protobufEmpty:
    type: "object"
    title: "A generic empty message that you can re-use to avoid defining duplicated\n\
      empty messages in your APIs. A typical example is to use it as the request\n\
      or the response type of an API method. For instance:"
    description: "service Foo {\n      rpc Bar(google.protobuf.Empty) returns (google.protobuf.Empty);\n\
      \    }\n\nThe JSON representation for `Empty` is empty JSON object `{}`."
  subStringMessage:
    type: "object"
    properties:
      value:
        type: "string"
    example:
      value: "value"
externalDocs:
  description: "More about gRPC-Gateway"
  url: "https://github.com/grpc-ecosystem/grpc-gateway"
